//
//  TermsOfUseView.swift
//  PulseCor
//

import SwiftUI

struct TermsOfUseView: View {
    var body: some View {
        ScrollView {
            VStack(spacing: 16) {

                PolicyCard(title: "1. Acceptance of Terms", content: "By downloading or using PulseCor, you agree to be bound by these Terms of Use. If you do not agree, please do not use the app.")

                PolicyCard(title: "2. Not Medical Advice", content: "PulseCor is a wellness and lifestyle companion app. It is not a medical device and does not provide medical advice, diagnosis, or treatment. Nothing in PulseCor should be interpreted as medical guidance.\n\nIf you have concerns about your cardiovascular health or any other medical condition, please consult a qualified healthcare professional. Do not delay seeking medical attention based on anything displayed within this app.")

                PolicyCard(title: "3. Intended Use", content: "PulseCor is designed to help you build awareness of how your daily lifestyle habits may affect your general wellbeing. It is intended for informational and motivational purposes only.\n\nThe app is intended for adults aged 18 and over. Use by individuals under 13 is not permitted.")

                PolicyCard(title: "4. Accuracy of Information", content: "The educational content, health tips, and general information provided within PulseCor are sourced from reputable organisations including the NHS, the British Heart Foundation, the American Heart Association, and academic research. Whilst we endeavour to ensure content is accurate and up to date, we make no guarantee of completeness or medical accuracy.\n\nHealth tips and insights generated by the app are based on your self-reported check-in data. They are indicative only and should not be treated as clinical findings.")

                PolicyCard(title: "5. Cora — Your Wellness Companion", content: "Cora is a scripted wellness companion built using predefined conversation logic. Cora is not a real person, therapist, or medical professional. Any support, encouragement, or insights Cora provides are automated responses designed for general motivational use.")

                PolicyCard(title: "6. HealthKit Integration", content: "If you choose to connect Apple HealthKit, PulseCor will read health data from your device. We do not write any data back to HealthKit. You may revoke HealthKit permissions at any time. PulseCor does not use HealthKit data for any purpose other than displaying information to you within the app.")

                PolicyCard(title: "7. Limitation of Liability", content: "PulseCor and its developer accept no liability for any health outcomes, decisions, or actions taken based on information or insights provided by the app. Use of PulseCor is entirely at your own risk.")

                PolicyCard(title: "8. Intellectual Property", content: "All content, design, and functionality within PulseCor is the intellectual property of the developer. You may not reproduce, distribute, or create derivative works from any part of the app without prior written permission.")

                PolicyCard(title: "9. Changes to These Terms", content: "We reserve the right to update these terms at any time. Continued use of the app following any update constitutes your acceptance of the revised terms.")

                PolicyCard(title: "10. Governing Law", content: "These terms are governed by the laws of England and Wales.")

                Text("Last updated: March 2026")
                    .font(.system(size: 11))
                    .foregroundColor(Color("MainText").opacity(0.4))
                    .padding(.top, 4)
                    .padding(.bottom, 24)
            }
            .padding(.horizontal, 14)
            .padding(.top, 16)
        }
        .background(Color("MainBG"))
        .navigationTitle("Terms of Use")
        .toolbarBackground(Color("MainBG"), for: .navigationBar)
        .toolbarBackground(.visible, for: .navigationBar)
    }
}
